### ISSUE TITLE
TakeLatest only registering first saga in list of sagas

### ISSUE THREAD

**Issue by d-pollard** [agiledigital/typed-redux-saga#216] opened 2020-10-01 23:34 UTC
## Relative code

Please consider the following code snippet as you read through the issue below

```typescript
import { call, put, takeLatest } from 'typed-redux-saga';

function* initialLoad() {
  ...
}

function* logout() {
  ....
}

export function* authSaga() {
  yield takeLatest(actions.logout.type, logout);
  yield takeLatest(actions.initialLoadStart.type, initialLoad);
}
```

## Issue

When using the `typed-redux-saga` version of `takeLatest`, on the first seems to be registering properly; when calling `initialLoadStart`, the action is dispatched, but `initialLoad` is never called.

## Expected result

When using the same code, but using `takeLatest` from `redux-saga/effects` both sagas get registered and are invoked when the event is dispatched

**Comment by danielnixon** [comment] 2020-10-02 23:50
Don't forget you need to use `yield*`, not `yield`.

**Comment by danielnixon** [comment] 2020-10-02 23:51
Possible dupe of #43 and #27.

**Comment by d-pollard** [comment] 2020-10-03 19:50
Interesting, mind explaining what the extra * does? or is there somewhere I can read about it? Also, why would it catch the first action but not any of the others?

**Comment by tema1411** [comment] 2020-10-03 21:54
> Interesting, mind explaining what the extra * does? or is there somewhere I can read about it? Also, why would it catch the first action but not any of the others?

Hello) You can read here https://javascript.info/generators

**Closed** 2020-10-13 01:44 UTC

**Comment by HelKyle** [comment] 2020-11-04 09:52
Same issue here, I am still confused as, why the second `takeLeast` function is never called. Can someone help me out?

**Comment by HelKyle** [comment] 2020-11-07 13:54
After spending lots of time debugging, I found the key code from redux-saga as below.

```
const result = fn.apply(context, args)

// i.e. a generator function returns an iterator
if (is.iterator(result)) {
  return result
}
let resolved = false

const next = arg => {
  if (!resolved) {
    resolved = true
    // Only promises returned from fork will be interpreted. See #1573
    return { value: result, done: !is.promise(result) }
  } else {
    return { value: arg, done: true }
  }
}

return makeIterator(next)
```

[redux-saga source code](https://github.com/redux-saga/redux-saga/blob/f070f1bac9fdfdc2ce2e0a1c50f65101c793d695/packages/core/src/internal/effectRunnerMap.js#L30)

Description: If the effect returns an iterator, then return it directly, otherwise return a new one for iteration. 

All the Effect functions from typed-redux-saga are generator function now while original redux-saga effects return plain object.

This can explain why the first `takeLatest` works, while the second one would never be called if forget to add `*`.
