### ISSUE TITLE
Typing not enforced if `select` called without argument

### ISSUE THREAD

**Issue by nzankich** [agiledigital/typed-redux-saga#430] opened 2021-02-12 20:14 UTC
in redux the effect `select` can be called without an argument to get the full state
https://redux-saga.js.org/docs/api/#selectselector-args

If you call it without an argument in typed-redux-saga though it comes back as an `any` type

say this was the state
```
{
   user: {
      name: 'foo'
   }
}
```

```
const {user} = yield* select();
```

`user` will come back with an `any` type so something like `user.email` won't cause a TS error

I think that this may be hard to implement but there should at least be an note in the README warning about it

**Comment by nzankich** [comment] 2021-02-12 20:19
I ended up making something like this to fix
```
export const getAllState = (state: ReduxState) => state;
```

```
const {user} = yield* select(getAllState);
```

**Comment by danielnixon** [comment] 2021-03-11 00:51
This is probably a duplicate of https://github.com/agiledigital/typed-redux-saga/issues/12

**Closed** 2021-03-11 00:52 UTC
